### ISSUE TITLE
Update plotting function

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/socialmixr#129]
The `matrix_plot` function uses `fields::image.plot` which seems to have been [deprecated](https://search.r-project.org/CRAN/refmans/fields/html/image.plot.html) so this should be updated.

Other considerations relating to this function:
- should we replace it with a `ggplot2` equivalent, reducing the number of dependencies and thus partially addressing #124? 
- should we make this a `plot` S3 function, which could potentially eventually live in https://github.com/socialcontactdata/contactmatrix where it could be used also for contact matrices generated by other packages?

pinging @Bisaloo @lwillem for thoughts/views.

**Comment by Bisaloo** [comment]
For me:

- Yes to using ggplot2, which offers users more customization options
- Yes to making it a `plot()` / `autoplot()` function. My suggestion would be to put it directly in https://github.com/socialcontactdata/contactmatrix since it's one of the remaining items on the roadmap

**Comment by lwillem** [comment]
While ggplot2 has its advantages, I would recommend a less invasive change by switching to the updated function fields::imagePlot in this instance. This way, we remain within the base R plotting context. I can have a look at this next week. Reviewing the dependencies is certainly worthwhile, as well as the discussion about a generic plot() function.

**Comment by sbfnk** [comment]
Sounds like the short-term fix is @lwillem's suggestion, whereas in the slightly longer term we want to farm this out to the `contactmatrix` package (which will be imported by `socialmixr`).

**Comment by lwillem** [comment]
I updated the plot_matrix function as discussed. See #133 for more information.

**Comment by sbfnk** [comment]
Fixed in #133.
