### ISSUE TITLE
"filter" argument in contact_matrix

### ISSUE THREAD

**Issue by dlaydon** [epiforecasts/socialmixr#25]
Hi there

Is it possible to expand the documentation for the "filter" argument in the function "contact_matrix"? For example, to exclude household, school and workplace contacts (but include transport, leisure and "otherplace" contacts), is the following correct?

contact_matrix(polymod, countries = "United Kingdom", 
             filter = list(cnt_work = 0, cnt_school = 0, cnt_home = 0, cnt_transport = 1, cnt_leisure = 1, cnt_otherplace = 1) , 
             age.limits = seq(0, 75, 5), symmetric = TRUE)

It would be really helpful if a list of the possible options for filter could be provided, ideally with an explanation of how the flags work, and also perhaps their default values. Specifically, would inclusion of cnt_home = 1 and cnt_school =1 result in the "union" of home or school contacts, or the much smaller "intersection" of contacts at both home and school?

Many thanks!

**Comment by sbfnk** [comment]
I've added this to the documentation for `filter` - does it clarify things? There are also now 2 examples in the vignette in the linked PR.

"If multiple filters are given, they are all applied independently and in the sequence given."

**Comment by dlaydon** [comment]
Thank you. The examples in the vignette are excellent. In the documentation though, a list of the acceptable options (for each survey) would be very helpful. Some clarification on whether the union or intersection of filters are used would be great. Perhaps it might also be helpful to include some mention of the default behaviour? As in, which values of cnt_work etc. would be equivalent to not specifying any filters at all? Many thanks! (and sorry to be a pain!)

**Comment by sbfnk** [comment]
This is now also clarified with some examples in the vignette.
