### ISSUE TITLE
distorted y-axis format when asymmetry is set to TRUE

### ISSUE THREAD

**Issue by deusthindwa** [epiforecasts/socialmixr#29]
If asymmetry = TRUE, the y-axis for participant age loses its [..) format but when set asymmetry = FALSE it gives correct format as expected. Below are plots with asymmetry set to TRUE and FALSE

![Fig1_matrices1](https://user-images.githubusercontent.com/28508458/121186975-dffcb780-c867-11eb-8400-c2fcd59478ea.jpg)
![Fig1_matrices2](https://user-images.githubusercontent.com/28508458/121186993-e2f7a800-c867-11eb-96f1-26ddbbb08200.jpg)

**Comment by sbfnk** [comment]
Hi, sorry to not pick this up earlier - I can't see the figures, can you re-upload them (with the code to reproduce them) if this issue still exists, or else close it? Thanks!
