### ISSUE TITLE
`age.groups` variable in `contact.matrix()` not defined

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/socialmixr#40]
From https://github.com/epiforecasts/socialmixr/pull/37:

It seems that the change in 7dcfca5fdb3046f6d13e3c32824f0ba0a7d08038 reveals a hidden bug. The `age.group` variable in `contact_matrix()` is actually never defined. data.table was quite happy with it being `NULL`, as set initially but now it's registered as an actual global variable, it doesn't work:

https://github.com/epiforecasts/socialmixr/blob/c83358240dc751602ec4fb30c5dc901590563707/R/contact_matrix.r#L550-L555

**Comment by Bisaloo** [comment]
Since I see this confusion between this issue title & body: as a starting point, it can be worth investigating if this is a mixup between `age.group` vs `age.groups`.

**Comment by sbfnk** [comment]
I'm not sure what the problem is, `age.group` is defined as a column [here](https://github.com/epiforecasts/socialmixr/blob/c83358240dc751602ec4fb30c5dc901590563707/R/contact_matrix.r#L312)

**Comment by Bisaloo** [comment]
The error seems to precisely occur in `survey$contacts`:

https://github.com/epiforecasts/socialmixr/blob/c83358240dc751602ec4fb30c5dc901590563707/R/contact_matrix.r#L553-L555

**Comment by sbfnk** [comment]
This is a bug - there is no guarantee that the variable exists in `contacts`. It's probably worth reviewing all the weighing arguments are consistent and work together well as these were added by different contributors at different times. Tagging @lwillem who added the code for poststratification weights by age group.
