### ISSUE TITLE
Survey reference can never include a version number

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/socialmixr#42]
Relevant code chunk:

https://github.com/epiforecasts/socialmixr/blob/b7afd5054a35c36d2e624158daf349249f650b6e/R/get_survey.r#L52-L60

`reference` is created with a given list of elements and names in L52-57. This list notably doesn't include `"reference"` so unless I'm missing something, the `if` branch on L58-60 can never be explored.

Is that supposed to be 

```diff
-      if ("version" %in% names(reference)) { 
+      if ("version" %in% names(parsed_cite)) {
        reference[["note"]] <- paste("Version", parsed_cite$version)
      }
```

?

**Comment by sbfnk** [comment]
> Is that supposed to be

Yes, I think that's exactly right
