### ISSUE TITLE
Remove `bootstrap` argument from `contact_matrix()`

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/socialmixr#50]
The `bootstrap` argument in `contact_matrix()` is made completely redundant by the existence of the `n` argument:

- `bootstrap = TRUE` is implied by `n > 1`

https://github.com/epiforecasts/socialmixr/blob/fa4d164a2bae47e9913a18458ba8a1e3fbdb1e81/R/contact_matrix.r#L65

- `bootstrap = FALSE` implies `n = 1`

https://github.com/epiforecasts/socialmixr/blob/fa4d164a2bae47e9913a18458ba8a1e3fbdb1e81/R/contact_matrix.r#L592-L597

We should remove the `bootstrap` argument and always set it up `n > 1`. The only currently working situation that would be removed is `bootstrap = TRUE` & `n = 1`. But that doesn't make a lot of sense and should probably be considered a bug IMO.

**Comment by sbfnk** [comment]
There might be a use case for `bootstrap = TRUE` and `n = 1`: if replacing missing or estimated contact ages with sampled ages (see `estimated...` and `missing...` arguments) a user might want to manually re-sample multiple times with `n = 1` and every time also re-sample the estimated ages.

Perhaps a better solution would be to remove the `n` argument and provide a separate wrapper function to call `contact_matrix` multiple times with `bootstrap = TRUE`? It might come at the expense of speed as there will be things within `contact_matrix` that wouldn't have to be run every time but at the benefit of having a [more consistent return value](https://github.com/epiforecasts/socialmixr/blob/c3b40a42ea5e7f73c0372b55e138f4efa19491e7/R/contact_matrix.r#L795) for the `contact_matrix` function.
